# Extra projects{.tabset}

During Covid19 I have undertaken other additional learning and development tasks to keep me informed for my positions on Council and for my PhD work.

## Courses

### Coursa

| Course Name                                                  | Enrolment Date   | Paid       | Y/N  | Grade Achieved |
| ------------------------------------------------------------ | ---------------- | ---------- | ---- | -------------- |
| Using clinical health data for better healthcare             | 2019-07-01       | N          | 0.00 |                |
| A Life of Happiness and Fulfillment                          | 2020-04-04       | N          | 0.00 |                |
| Science Matters: Let's Talk About COVID-19                   | 2020-04-03       | N          | 0.00 |                |
| Reproducible Research                                        | 2020-04-21       | N          | 0.00 |                |
| Understanding Clinical Research: Behind the Statistics       | 2020-04-04       | N          | 0.00 |                |
| The Science of Well-Being                                    | 2020-04-21       | N          | 0.00 |                |
| Learning How to Learn: Powerful mental tools to help you master tough subjects | 2020-04-04       | N          | 0.00 |                |
| Mindshift: Break Through Obstacles to Learning and Discover Your | Hidden Potential | 2020-04-04 | N    | 0.00           |
| Mountains 101                                                | 2020-04-04       | N          | 0.00 |                |
| Machine Learning                                             | 2020-04-04       | N          | 0.00 |                |

## Seminars


## Teaching

### ANU: Climate Change

### ANU: Masters Projects

## Community projects
